site_name: jeeves
repo_url: https://github.com/jeeves-sh/jeeves-shell
repo_name: jeeves-shell
copyright: Copyright &copy; 2022 jeeves.sh


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings
  - iolanta
  - macros:
      modules:
        - macros

theme:
  name: material
  features:
    - header.autohide
    - navigation.indexes
    - content.code.annotate
    - navigation.sections
