site_name: jeeves
repo_url: https://github.com/jeeves-sh/jeeves-shell
repo_name: jeeves-shell
copyright: Copyright &copy; 2022 jeeves.sh

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings
# - octadocs
# - octadocs_adr
  - macros:
      modules:
        - macros

theme:
  name: material
