site_name: jeeves
repo_url: https://github.com/jeeves-sh/jeeves-shell
repo_name: jeeves-sh/jeeves-shell
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2023 jeeves.sh

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings
  - awesome-pages
  - iolanta
  - macros:
      modules:
        - macros

theme:
  name: material
  icon:
    logo: material/bow-tie
  features:
    - content.action.edit
    - header.autohide
    - navigation.indexes
    - content.code.annotate
    - navigation.sections

#extra_javascript:
#  - assets/termynal/termynal.js

extra_css:
  - assets/termynal/termynal.css
