[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "jeeves-core"
description = "Pythonic replacement for GNU Make: core"
version = "1.0.5"
license = "MIT"

authors = []

readme = "README.md"

repository = "https://github.com/jeeves-sh/jeeves-core"

keywords = []

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.scripts]
j = "jeeves_core.cli:app"


[tool.poetry.dependencies]
python = ">=3.8,<4.0"
typer = "^0.7.0"
documented = "^0.1.1"


[tool.poetry.group.dev.dependencies]
mypy = "^0.910"
flake8 = "<4.0.0"

safety = "^1.10"

pytest = "^6.2"
pytest-cov = "^2.12"
pytest-randomly = "^3.8"

m2r2 = "^0.2"
tomlkit = "^0.7"
flakehell = "^0.9.0"
mkdocs = "^1.2.2"
mkdocstrings = "^0.16.2"
mkdocs-material = "^7.3.2"
wemake-python-styleguide = "^0.17.0"

jinja2 = "<3.0"       # Otherwise, `mkdocstrings` will fail
markupsafe = "<2.1"   # Otherwise, `jinja2` will fail

[tool.flakehell]
base = "https://raw.githubusercontent.com/Recall-Masters/standards/main/pyproject.toml"

# https://github.com/flakehell/flakehell/issues/10#issuecomment-822720074
extended_default_ignore=[]  # add this


[tool.flakehell.exceptions."tests/modules/**"]
pyflakes = [
    # %s imported but unused
    "-F401",
]


[tool.flakehell.exceptions."jeeves_core/entry_points.py"]
wemake-python-styleguide = [
  "-WPS433",
  "-WPS440",
]
pyflakes = [
    # %s imported but unused
    "-F401",
]
